version: '3.8'
services:
  mobile_id_server:
    build: .
    container_name: mobile_id_server
    ports:
      - $MOBILE_ID_SERVER_PORT:8000
    volumes:
      - type: bind
        source: ./base.pass
        target: /data/base.pass
      - type: bind
        source: ./certificates
        target: /data/certificates
      - type: bind
        source: ./examples
        target: /data/examples
      - type: bind
        source: ./include
        target: /data/include
      - type: bind
        source: ./passes
        target: /data/passes
      - type: bind
        source: ./static
        target: /data/static
      - type: bind
        source: ./templates
        target: /data/templates
      - type: bind
        source: ./config.py
        target: /data/config.py
      - type: bind
        source: ./main.py
        target: /data/main.py
    restart: always
    command: ["/bin/bash", "-c", "python3.9 -m uvicorn main:app --reload --host 0.0.0.0"]
